<?php

$oldElements = [
    [
        'atomic_number'          => '1',
        'symbol'                 => 'H',
        'name_cz'                => 'vodík',
        'name_en'                => 'Hydrogen',
        'name_la'                => 'Hydrogenium',
        'periodical_group'       => '1',
        'period'                 => '1',
        'atomic_weight'          => '1',
        'density'                => '0.00008988',
        'melting_point'          => '14.01',
        'boiling_point'          => '20.28',
        'specific_heat_capacity' => '14.304',
        'electronegativity'      => '2.2',
    ],
    [
        'atomic_number'          => '2',
        'symbol'                 => 'He',
        'name_cz'                => 'helium',
        'name_en'                => 'Helium',
        'name_la'                => 'Helium',
        'periodical_group'       => '18',
        'period'                 => '1',
        'atomic_weight'          => '4.002602(2)',
        'density'                => '0.0001785',
        'melting_point'          => null,
        'boiling_point'          => '4.22',
        'specific_heat_capacity' => '5.193',
        'electronegativity'      => '0',
    ],
    [
        'atomic_number'          => '3',
        'symbol'                 => 'Li',
        'name_cz'                => 'lithium',
        'name_en'                => 'Lithium',
        'name_la'                => 'Lithium',
        'periodical_group'       => '1',
        'period'                 => '2',
        'atomic_weight'          => '6.94',
        'density'                => '0.534',
        'melting_point'          => '453.69',
        'boiling_point'          => '1560',
        'specific_heat_capacity' => '3.582',
        'electronegativity'      => '0.98',
    ],
    [
        'atomic_number'          => '4',
        'symbol'                 => 'Be',
        'name_cz'                => 'beryllium',
        'name_en'                => 'Beryllium',
        'name_la'                => 'Beryllium',
        'periodical_group'       => '2',
        'period'                 => '2',
        'atomic_weight'          => '9.0121831(5)',
        'density'                => '1.85',
        'melting_point'          => '1560',
        'boiling_point'          => '2742',
        'specific_heat_capacity' => '1.825',
        'electronegativity'      => '1.57',
    ],
    [
        'atomic_number'          => '5',
        'symbol'                 => 'B',
        'name_cz'                => 'bor',
        'name_en'                => 'Boron',
        'name_la'                => 'Borium',
        'periodical_group'       => '13',
        'period'                 => '2',
        'atomic_weight'          => '10.81',
        'density'                => '2.34',
        'melting_point'          => '2349',
        'boiling_point'          => '4200',
        'specific_heat_capacity' => '1.026',
        'electronegativity'      => '2.04',
    ],
    [
        'atomic_number'          => '6',
        'symbol'                 => 'C',
        'name_cz'                => 'uhlík',
        'name_en'                => 'Carbon',
        'name_la'                => 'Carbonium nebo Carboneum',
        'periodical_group'       => '14',
        'period'                 => '2',
        'atomic_weight'          => '12.011',
        'density'                => '2.267',
        'melting_point'          => '4000',
        'boiling_point'          => '4300',
        'specific_heat_capacity' => '0.709',
        'electronegativity'      => '2.55',
    ],
    [
        'atomic_number'          => '7',
        'symbol'                 => 'N',
        'name_cz'                => 'dusík',
        'name_en'                => 'Nitrogen',
        'name_la'                => 'Nitrogenium',
        'periodical_group'       => '15',
        'period'                 => '2',
        'atomic_weight'          => '14.007',
        'density'                => '0.0012506',
        'melting_point'          => '63.15',
        'boiling_point'          => '77.36',
        'specific_heat_capacity' => '1.04',
        'electronegativity'      => '3.04',
    ],
    [
        'atomic_number'          => '8',
        'symbol'                 => 'O',
        'name_cz'                => 'kyslík',
        'name_en'                => 'Oxygen',
        'name_la'                => 'Oxygenium',
        'periodical_group'       => '16',
        'period'                 => '2',
        'atomic_weight'          => '15.999',
        'density'                => '0.001429',
        'melting_point'          => '54.36',
        'boiling_point'          => '90.2',
        'specific_heat_capacity' => '0.918',
        'electronegativity'      => '3.44',
    ],
    [
        'atomic_number'          => '9',
        'symbol'                 => 'F',
        'name_cz'                => 'fluor',
        'name_en'                => 'Fluorine',
        'name_la'                => 'Fluorum',
        'periodical_group'       => '17',
        'period'                 => '2',
        'atomic_weight'          => '18.998403163(6)',
        'density'                => '0.001696',
        'melting_point'          => '53.53',
        'boiling_point'          => '85.03',
        'specific_heat_capacity' => '0.824',
        'electronegativity'      => '3.98',
    ],
    [
        'atomic_number'          => '10',
        'symbol'                 => 'Ne',
        'name_cz'                => 'neon',
        'name_en'                => 'Neon',
        'name_la'                => 'Neon',
        'periodical_group'       => '18',
        'period'                 => '2',
        'atomic_weight'          => '20.1797(6)',
        'density'                => '0.0008999',
        'melting_point'          => '24.56',
        'boiling_point'          => '27.07',
        'specific_heat_capacity' => '1.03',
        'electronegativity'      => '0',
    ],
    [
        'atomic_number'          => '11',
        'symbol'                 => 'Na',
        'name_cz'                => 'sodík',
        'name_en'                => 'Sodium',
        'name_la'                => 'Natrium',
        'periodical_group'       => '1',
        'period'                 => '3',
        'atomic_weight'          => '22.98976928(2)',
        'density'                => '0.971',
        'melting_point'          => '370.87',
        'boiling_point'          => '1156',
        'specific_heat_capacity' => '1.228',
        'electronegativity'      => '0.93',
    ],
    [
        'atomic_number'          => '12',
        'symbol'                 => 'Mg',
        'name_cz'                => 'hořčík',
        'name_en'                => 'Magnesium',
        'name_la'                => 'Magnesium',
        'periodical_group'       => '2',
        'period'                 => '3',
        'atomic_weight'          => '24.305',
        'density'                => '1.738',
        'melting_point'          => '923',
        'boiling_point'          => '1363',
        'specific_heat_capacity' => '1.023',
        'electronegativity'      => '1.31',
    ],
    [
        'atomic_number'          => '13',
        'symbol'                 => 'Al',
        'name_cz'                => 'hliník',
        'name_en'                => 'Aluminium',
        'name_la'                => 'Aluminium',
        'periodical_group'       => '13',
        'period'                 => '3',
        'atomic_weight'          => '26.9815384(3)',
        'density'                => '2.698',
        'melting_point'          => '933.47',
        'boiling_point'          => '2792',
        'specific_heat_capacity' => '0.897',
        'electronegativity'      => '1.61',
    ],
    [
        'atomic_number'          => '14',
        'symbol'                 => 'Si',
        'name_cz'                => 'křemík',
        'name_en'                => 'Silicon',
        'name_la'                => 'Silicium',
        'periodical_group'       => '14',
        'period'                 => '3',
        'atomic_weight'          => '28.085',
        'density'                => '2.3296',
        'melting_point'          => '1687',
        'boiling_point'          => '3538',
        'specific_heat_capacity' => '0.705',
        'electronegativity'      => '1.9',
    ],
    [
        'atomic_number'          => '15',
        'symbol'                 => 'P',
        'name_cz'                => 'fosfor',
        'name_en'                => 'Phosphorus',
        'name_la'                => 'Phosphorus',
        'periodical_group'       => '15',
        'period'                 => '3',
        'atomic_weight'          => '30.973761998(5)',
        'density'                => '1.82',
        'melting_point'          => '317.3',
        'boiling_point'          => '550',
        'specific_heat_capacity' => '0.769',
        'electronegativity'      => '2.19',
    ],
    [
        'atomic_number'          => '16',
        'symbol'                 => 'S',
        'name_cz'                => 'síra',
        'name_en'                => 'Sulfur',
        'name_la'                => 'Sulphur',
        'periodical_group'       => '16',
        'period'                 => '3',
        'atomic_weight'          => '32.06',
        'density'                => '2.067',
        'melting_point'          => '388.36',
        'boiling_point'          => '717.87',
        'specific_heat_capacity' => '0.71',
        'electronegativity'      => '2.58',
    ],
    [
        'atomic_number'          => '17',
        'symbol'                 => 'Cl',
        'name_cz'                => 'chlor',
        'name_en'                => 'Chlorine',
        'name_la'                => 'Chlorum',
        'periodical_group'       => '17',
        'period'                 => '3',
        'atomic_weight'          => '35.45',
        'density'                => '0.003214',
        'melting_point'          => '171.6',
        'boiling_point'          => '239.11',
        'specific_heat_capacity' => '0.479',
        'electronegativity'      => '3.16',
    ],
    [
        'atomic_number'          => '18',
        'symbol'                 => 'Ar',
        'name_cz'                => 'argon',
        'name_en'                => 'Argon',
        'name_la'                => 'Argon',
        'periodical_group'       => '18',
        'period'                 => '3',
        'atomic_weight'          => '39.95',
        'density'                => '0.0017837',
        'melting_point'          => '83.8',
        'boiling_point'          => '87.3',
        'specific_heat_capacity' => '0.52',
        'electronegativity'      => '0',
    ],
    [
        'atomic_number'          => '19',
        'symbol'                 => 'K',
        'name_cz'                => 'draslík',
        'name_en'                => 'Potassium',
        'name_la'                => 'Kalium',
        'periodical_group'       => '1',
        'period'                 => '4',
        'atomic_weight'          => '39.0983(1)',
        'density'                => '0.862',
        'melting_point'          => '336.53',
        'boiling_point'          => '1032',
        'specific_heat_capacity' => '0.757',
        'electronegativity'      => '0.82',
    ],
    [
        'atomic_number'          => '20',
        'symbol'                 => 'Ca',
        'name_cz'                => 'vápník',
        'name_en'                => 'Calcium',
        'name_la'                => 'Calcium',
        'periodical_group'       => '2',
        'period'                 => '4',
        'atomic_weight'          => '40.078(4)',
        'density'                => '1.54',
        'melting_point'          => '1115',
        'boiling_point'          => '1757',
        'specific_heat_capacity' => '0.647',
        'electronegativity'      => '1',
    ],
    [
        'atomic_number'          => '21',
        'symbol'                 => 'Sc',
        'name_cz'                => 'skandium',
        'name_en'                => 'Scandium',
        'name_la'                => 'Scandium',
        'periodical_group'       => '3',
        'period'                 => '4',
        'atomic_weight'          => '44.955908(5)',
        'density'                => '2.989',
        'melting_point'          => '1814',
        'boiling_point'          => '3109',
        'specific_heat_capacity' => '0.568',
        'electronegativity'      => '1.36',
    ],
    [
        'atomic_number'          => '22',
        'symbol'                 => 'Ti',
        'name_cz'                => 'titan',
        'name_en'                => 'Titanium',
        'name_la'                => 'Titanium',
        'periodical_group'       => '4',
        'period'                 => '4',
        'atomic_weight'          => '47.867(1)',
        'density'                => '4.54',
        'melting_point'          => '1941',
        'boiling_point'          => '3560',
        'specific_heat_capacity' => '0.523',
        'electronegativity'      => '1.54',
    ],
    [
        'atomic_number'          => '23',
        'symbol'                 => 'V',
        'name_cz'                => 'vanad',
        'name_en'                => 'Vanadium',
        'name_la'                => 'Vanadium',
        'periodical_group'       => '5',
        'period'                 => '4',
        'atomic_weight'          => '50.9415(1)',
        'density'                => '6.11',
        'melting_point'          => '2183',
        'boiling_point'          => '3680',
        'specific_heat_capacity' => '0.489',
        'electronegativity'      => '1.63',
    ],
    [
        'atomic_number'          => '24',
        'symbol'                 => 'Cr',
        'name_cz'                => 'chrom',
        'name_en'                => 'Chromium',
        'name_la'                => 'Chromium',
        'periodical_group'       => '6',
        'period'                 => '4',
        'atomic_weight'          => '51.9961(6)',
        'density'                => '7.15',
        'melting_point'          => '2180',
        'boiling_point'          => '2944',
        'specific_heat_capacity' => '0.449',
        'electronegativity'      => '1.66',
    ],
    [
        'atomic_number'          => '25',
        'symbol'                 => 'Mn',
        'name_cz'                => 'mangan',
        'name_en'                => 'Manganese',
        'name_la'                => 'Manganum',
        'periodical_group'       => '7',
        'period'                 => '4',
        'atomic_weight'          => '54.938043(2)',
        'density'                => '7.44',
        'melting_point'          => '1519',
        'boiling_point'          => '2334',
        'specific_heat_capacity' => '0.479',
        'electronegativity'      => '1.55',
    ],
    [
        'atomic_number'          => '26',
        'symbol'                 => 'Fe',
        'name_cz'                => 'železo',
        'name_en'                => 'Iron',
        'name_la'                => 'Ferrum',
        'periodical_group'       => '8',
        'period'                 => '4',
        'atomic_weight'          => '55.845(2)',
        'density'                => '7.874',
        'melting_point'          => '1811',
        'boiling_point'          => '3134',
        'specific_heat_capacity' => '0.449',
        'electronegativity'      => '1.83',
    ],
    [
        'atomic_number'          => '27',
        'symbol'                 => 'Co',
        'name_cz'                => 'kobalt',
        'name_en'                => 'Cobalt',
        'name_la'                => 'Cobaltum',
        'periodical_group'       => '9',
        'period'                 => '4',
        'atomic_weight'          => '58.933194(3)',
        'density'                => '8.86',
        'melting_point'          => '1768',
        'boiling_point'          => '3200',
        'specific_heat_capacity' => '0.421',
        'electronegativity'      => '1.88',
    ],
    [
        'atomic_number'          => '28',
        'symbol'                 => 'Ni',
        'name_cz'                => 'nikl',
        'name_en'                => 'Nickel',
        'name_la'                => 'Niccolum',
        'periodical_group'       => '10',
        'period'                 => '4',
        'atomic_weight'          => '58.6934(4)',
        'density'                => '8.912',
        'melting_point'          => '1728',
        'boiling_point'          => '3186',
        'specific_heat_capacity' => '0.444',
        'electronegativity'      => '1.91',
    ],
    [
        'atomic_number'          => '29',
        'symbol'                 => 'Cu',
        'name_cz'                => 'měď',
        'name_en'                => 'Copper',
        'name_la'                => 'Cuprum',
        'periodical_group'       => '11',
        'period'                 => '4',
        'atomic_weight'          => '63.546(3)',
        'density'                => '8.96',
        'melting_point'          => '1357.77',
        'boiling_point'          => '2835',
        'specific_heat_capacity' => '0.385',
        'electronegativity'      => '1.9',
    ],
    [
        'atomic_number'          => '30',
        'symbol'                 => 'Zn',
        'name_cz'                => 'zinek',
        'name_en'                => 'Zinc',
        'name_la'                => 'Zincum',
        'periodical_group'       => '12',
        'period'                 => '4',
        'atomic_weight'          => '65.38(2)',
        'density'                => '7.134',
        'melting_point'          => '692.88',
        'boiling_point'          => '1180',
        'specific_heat_capacity' => '0.388',
        'electronegativity'      => '1.65',
    ],
    [
        'atomic_number'          => '31',
        'symbol'                 => 'Ga',
        'name_cz'                => 'gallium',
        'name_en'                => 'Gallium',
        'name_la'                => 'Gallium',
        'periodical_group'       => '13',
        'period'                 => '4',
        'atomic_weight'          => '69.723(1)',
        'density'                => '5.907',
        'melting_point'          => '302.915',
        'boiling_point'          => '2673',
        'specific_heat_capacity' => '0.371',
        'electronegativity'      => '1.81',
    ],
    [
        'atomic_number'          => '32',
        'symbol'                 => 'Ge',
        'name_cz'                => 'germanium',
        'name_en'                => 'Germanium',
        'name_la'                => 'Germanium',
        'periodical_group'       => '14',
        'period'                 => '4',
        'atomic_weight'          => '72.630(8)',
        'density'                => '5.323',
        'melting_point'          => '1211.4',
        'boiling_point'          => '3106',
        'specific_heat_capacity' => '0.32',
        'electronegativity'      => '2.01',
    ],
    [
        'atomic_number'          => '33',
        'symbol'                 => 'As',
        'name_cz'                => 'arsen',
        'name_en'                => 'Arsenic',
        'name_la'                => 'Arsenicum',
        'periodical_group'       => '15',
        'period'                 => '4',
        'atomic_weight'          => '74.921595(6)',
        'density'                => '5.776',
        'melting_point'          => '1090',
        'boiling_point'          => '887',
        'specific_heat_capacity' => '0.329',
        'electronegativity'      => '2.18',
    ],
    [
        'atomic_number'          => '34',
        'symbol'                 => 'Se',
        'name_cz'                => 'selen',
        'name_en'                => 'Selenium',
        'name_la'                => 'Selenium',
        'periodical_group'       => '16',
        'period'                 => '4',
        'atomic_weight'          => '78.971(8)',
        'density'                => '4.809',
        'melting_point'          => '453',
        'boiling_point'          => '958',
        'specific_heat_capacity' => '0.321',
        'electronegativity'      => '2.55',
    ],
    [
        'atomic_number'          => '35',
        'symbol'                 => 'Br',
        'name_cz'                => 'brom',
        'name_en'                => 'Bromine',
        'name_la'                => 'Bromum',
        'periodical_group'       => '17',
        'period'                 => '4',
        'atomic_weight'          => '79.904',
        'density'                => '3.122',
        'melting_point'          => '265.8',
        'boiling_point'          => '332',
        'specific_heat_capacity' => '0.474',
        'electronegativity'      => '2.96',
    ],
    [
        'atomic_number'          => '36',
        'symbol'                 => 'Kr',
        'name_cz'                => 'krypton',
        'name_en'                => 'Krypton',
        'name_la'                => 'Krypton',
        'periodical_group'       => '18',
        'period'                 => '4',
        'atomic_weight'          => '83.798(2)',
        'density'                => '0.003733',
        'melting_point'          => '115.79',
        'boiling_point'          => '119.93',
        'specific_heat_capacity' => '0.248',
        'electronegativity'      => '3',
    ],
    [
        'atomic_number'          => '37',
        'symbol'                 => 'Rb',
        'name_cz'                => 'rubidium',
        'name_en'                => 'Rubidium',
        'name_la'                => 'Rubidium',
        'periodical_group'       => '1',
        'period'                 => '5',
        'atomic_weight'          => '85.4678(3)',
        'density'                => '1.532',
        'melting_point'          => '312.46',
        'boiling_point'          => '961',
        'specific_heat_capacity' => '0.363',
        'electronegativity'      => '0.82',
    ],
    [
        'atomic_number'          => '38',
        'symbol'                 => 'Sr',
        'name_cz'                => 'stroncium',
        'name_en'                => 'Strontium',
        'name_la'                => 'Strontium',
        'periodical_group'       => '2',
        'period'                 => '5',
        'atomic_weight'          => '87.62(1)',
        'density'                => '2.64',
        'melting_point'          => '1050',
        'boiling_point'          => '1655',
        'specific_heat_capacity' => '0.301',
        'electronegativity'      => '0.95',
    ],
    [
        'atomic_number'          => '39',
        'symbol'                 => 'Y',
        'name_cz'                => 'yttrium',
        'name_en'                => 'Yttrium',
        'name_la'                => 'Yttrium',
        'periodical_group'       => '3',
        'period'                 => '5',
        'atomic_weight'          => '88.90584(1)',
        'density'                => '4.469',
        'melting_point'          => '1799',
        'boiling_point'          => '3609',
        'specific_heat_capacity' => '0.298',
        'electronegativity'      => '1.22',
    ],
    [
        'atomic_number'          => '40',
        'symbol'                 => 'Zr',
        'name_cz'                => 'zirkonium',
        'name_en'                => 'Zirconium',
        'name_la'                => 'Zirconium',
        'periodical_group'       => '4',
        'period'                 => '5',
        'atomic_weight'          => '91.224(2)',
        'density'                => '6.506',
        'melting_point'          => '2128',
        'boiling_point'          => '4682',
        'specific_heat_capacity' => '0.278',
        'electronegativity'      => '1.33',
    ],
    [
        'atomic_number'          => '41',
        'symbol'                 => 'Nb',
        'name_cz'                => 'niob',
        'name_en'                => 'Niobium',
        'name_la'                => 'Niobium',
        'periodical_group'       => '5',
        'period'                 => '5',
        'atomic_weight'          => '92.90637(1)',
        'density'                => '8.57',
        'melting_point'          => '2750',
        'boiling_point'          => '5017',
        'specific_heat_capacity' => '0.265',
        'electronegativity'      => '1.6',
    ],
    [
        'atomic_number'          => '42',
        'symbol'                 => 'Mo',
        'name_cz'                => 'molybden',
        'name_en'                => 'Molybdenum',
        'name_la'                => 'Molybdenum',
        'periodical_group'       => '6',
        'period'                 => '5',
        'atomic_weight'          => '95.95(1)',
        'density'                => '10.22',
        'melting_point'          => '2896',
        'boiling_point'          => '4912',
        'specific_heat_capacity' => '0.251',
        'electronegativity'      => '2.16',
    ],
    [
        'atomic_number'          => '43',
        'symbol'                 => 'Tc',
        'name_cz'                => 'technecium',
        'name_en'                => 'Technetium',
        'name_la'                => 'Technetium',
        'periodical_group'       => '7',
        'period'                 => '5',
        'atomic_weight'          => '[98]',
        'density'                => '11.5',
        'melting_point'          => '2430',
        'boiling_point'          => '4538',
        'specific_heat_capacity' => null,
        'electronegativity'      => '1.9',
    ],
    [
        'atomic_number'          => '44',
        'symbol'                 => 'Ru',
        'name_cz'                => 'ruthenium',
        'name_en'                => 'Ruthenium',
        'name_la'                => 'Ruthenium',
        'periodical_group'       => '8',
        'period'                 => '5',
        'atomic_weight'          => '101.07(2)',
        'density'                => '12.37',
        'melting_point'          => '2607',
        'boiling_point'          => '4423',
        'specific_heat_capacity' => '0.238',
        'electronegativity'      => '2.2',
    ],
    [
        'atomic_number'          => '45',
        'symbol'                 => 'Rh',
        'name_cz'                => 'rhodium',
        'name_en'                => 'Rhodium',
        'name_la'                => 'Rhodium',
        'periodical_group'       => '9',
        'period'                 => '5',
        'atomic_weight'          => '102.90549(2)',
        'density'                => '12.41',
        'melting_point'          => '2237',
        'boiling_point'          => '3968',
        'specific_heat_capacity' => '0.243',
        'electronegativity'      => '2.28',
    ],
    [
        'atomic_number'          => '46',
        'symbol'                 => 'Pd',
        'name_cz'                => 'palladium',
        'name_en'                => 'Palladium',
        'name_la'                => 'Palladium',
        'periodical_group'       => '10',
        'period'                 => '5',
        'atomic_weight'          => '106.42(1)',
        'density'                => '12.02',
        'melting_point'          => '1828.05',
        'boiling_point'          => '3236',
        'specific_heat_capacity' => '0.244',
        'electronegativity'      => '2.2',
    ],
    [
        'atomic_number'          => '47',
        'symbol'                 => 'Ag',
        'name_cz'                => 'stříbro',
        'name_en'                => 'Silver',
        'name_la'                => 'Argentum',
        'periodical_group'       => '11',
        'period'                 => '5',
        'atomic_weight'          => '107.8682(2)',
        'density'                => '10.501',
        'melting_point'          => '1234.93',
        'boiling_point'          => '2435',
        'specific_heat_capacity' => '0.235',
        'electronegativity'      => '1.93',
    ],
    [
        'atomic_number'          => '48',
        'symbol'                 => 'Cd',
        'name_cz'                => 'kadmium',
        'name_en'                => 'Cadmium',
        'name_la'                => 'Cadmium',
        'periodical_group'       => '12',
        'period'                 => '5',
        'atomic_weight'          => '112.414(4)',
        'density'                => '8.69',
        'melting_point'          => '594.22',
        'boiling_point'          => '1040',
        'specific_heat_capacity' => '0.232',
        'electronegativity'      => '1.69',
    ],
    [
        'atomic_number'          => '49',
        'symbol'                 => 'In',
        'name_cz'                => 'indium',
        'name_en'                => 'Indium',
        'name_la'                => 'Indium',
        'periodical_group'       => '13',
        'period'                 => '5',
        'atomic_weight'          => '114.818(1)',
        'density'                => '7.31',
        'melting_point'          => '429.75',
        'boiling_point'          => '2345',
        'specific_heat_capacity' => '0.233',
        'electronegativity'      => '1.78',
    ],
    [
        'atomic_number'          => '50',
        'symbol'                 => 'Sn',
        'name_cz'                => 'cín',
        'name_en'                => 'Tin',
        'name_la'                => 'Stannum',
        'periodical_group'       => '14',
        'period'                 => '5',
        'atomic_weight'          => '118.710(7)',
        'density'                => '7.287',
        'melting_point'          => '505.08',
        'boiling_point'          => '2875',
        'specific_heat_capacity' => '0.228',
        'electronegativity'      => '1.96',
    ],
    [
        'atomic_number'          => '51',
        'symbol'                 => 'Sb',
        'name_cz'                => 'antimon',
        'name_en'                => 'Antimony',
        'name_la'                => 'Atibium',
        'periodical_group'       => '15',
        'period'                 => '5',
        'atomic_weight'          => '121.760(1)',
        'density'                => '6.685',
        'melting_point'          => '903.78',
        'boiling_point'          => '1860',
        'specific_heat_capacity' => '0.207',
        'electronegativity'      => '2.05',
    ],
    [
        'atomic_number'          => '52',
        'symbol'                 => 'Te',
        'name_cz'                => 'tellur',
        'name_en'                => 'Tellurium',
        'name_la'                => 'Tellurium',
        'periodical_group'       => '16',
        'period'                 => '5',
        'atomic_weight'          => '127.60(3)',
        'density'                => '6.232',
        'melting_point'          => '722.66',
        'boiling_point'          => '1261',
        'specific_heat_capacity' => '0.202',
        'electronegativity'      => '2.1',
    ],
    [
        'atomic_number'          => '53',
        'symbol'                 => 'I',
        'name_cz'                => 'jod',
        'name_en'                => 'Iodine',
        'name_la'                => 'Iodum',
        'periodical_group'       => '17',
        'period'                 => '5',
        'atomic_weight'          => '126.90447(3)',
        'density'                => '4.93',
        'melting_point'          => '386.85',
        'boiling_point'          => '457.4',
        'specific_heat_capacity' => '0.214',
        'electronegativity'      => '2.66',
    ],
    [
        'atomic_number'          => '54',
        'symbol'                 => 'Xe',
        'name_cz'                => 'xenon',
        'name_en'                => 'Xenon',
        'name_la'                => 'Xenon',
        'periodical_group'       => '18',
        'period'                 => '5',
        'atomic_weight'          => '131.293(6)',
        'density'                => '0.005887',
        'melting_point'          => '161.4',
        'boiling_point'          => '165.03',
        'specific_heat_capacity' => '0.158',
        'electronegativity'      => '2.6',
    ],
    [
        'atomic_number'          => '55',
        'symbol'                 => 'Cs',
        'name_cz'                => 'cesium',
        'name_en'                => 'Caesium',
        'name_la'                => 'Caesium',
        'periodical_group'       => '1',
        'period'                 => '6',
        'atomic_weight'          => '132.90545196(6)',
        'density'                => '1.873',
        'melting_point'          => '301.59',
        'boiling_point'          => '944',
        'specific_heat_capacity' => '0.242',
        'electronegativity'      => '0.79',
    ],
    [
        'atomic_number'          => '56',
        'symbol'                 => 'Ba',
        'name_cz'                => 'baryum',
        'name_en'                => 'Barium',
        'name_la'                => 'Barium',
        'periodical_group'       => '2',
        'period'                 => '6',
        'atomic_weight'          => '137.327(7)',
        'density'                => '3.594',
        'melting_point'          => '1000',
        'boiling_point'          => '2170',
        'specific_heat_capacity' => '0.204',
        'electronegativity'      => '0.89',
    ],
    [
        'atomic_number'          => '57',
        'symbol'                 => 'La',
        'name_cz'                => 'lanthan',
        'name_en'                => 'Lanthanum',
        'name_la'                => 'Lanthanum',
        'periodical_group'       => null,
        'period'                 => '6',
        'atomic_weight'          => '138.90547(7)',
        'density'                => '6.145',
        'melting_point'          => '1193',
        'boiling_point'          => '3737',
        'specific_heat_capacity' => '0.195',
        'electronegativity'      => '1.1',
    ],
    [
        'atomic_number'          => '58',
        'symbol'                 => 'Ce',
        'name_cz'                => 'cer',
        'name_en'                => 'Cerium',
        'name_la'                => 'Cerium',
        'periodical_group'       => null,
        'period'                 => '6',
        'atomic_weight'          => '140.116(1)',
        'density'                => '6.77',
        'melting_point'          => '1068',
        'boiling_point'          => '3716',
        'specific_heat_capacity' => '0.192',
        'electronegativity'      => '1.12',
    ],
    [
        'atomic_number'          => '59',
        'symbol'                 => 'Pr',
        'name_cz'                => 'praseodym',
        'name_en'                => 'Praseodymium',
        'name_la'                => 'Praseodymium',
        'periodical_group'       => null,
        'period'                 => '6',
        'atomic_weight'          => '140.90766(1)',
        'density'                => '6.773',
        'melting_point'          => '1208',
        'boiling_point'          => '3793',
        'specific_heat_capacity' => '0.193',
        'electronegativity'      => '1.13',
    ],
    [
        'atomic_number'          => '60',
        'symbol'                 => 'Nd',
        'name_cz'                => 'neodym',
        'name_en'                => 'Neodymium',
        'name_la'                => 'Neodymium',
        'periodical_group'       => null,
        'period'                 => '6',
        'atomic_weight'          => '144.242(3)',
        'density'                => '7.007',
        'melting_point'          => '1297',
        'boiling_point'          => '3347',
        'specific_heat_capacity' => '0.19',
        'electronegativity'      => '1.14',
    ],
    [
        'atomic_number'          => '61',
        'symbol'                 => 'Pm',
        'name_cz'                => 'promethium',
        'name_en'                => 'Promethium',
        'name_la'                => 'Promethium',
        'periodical_group'       => null,
        'period'                 => '6',
        'atomic_weight'          => '[145]',
        'density'                => '7.26',
        'melting_point'          => '1315',
        'boiling_point'          => '3273',
        'specific_heat_capacity' => null,
        'electronegativity'      => '1.13',
    ],
    [
        'atomic_number'          => '62',
        'symbol'                 => 'Sm',
        'name_cz'                => 'samarium',
        'name_en'                => 'Samarium',
        'name_la'                => 'Samarium',
        'periodical_group'       => null,
        'period'                 => '6',
        'atomic_weight'          => '150.36(2)',
        'density'                => '7.52',
        'melting_point'          => '1345',
        'boiling_point'          => '2067',
        'specific_heat_capacity' => '0.197',
        'electronegativity'      => '1.17',
    ],
    [
        'atomic_number'          => '63',
        'symbol'                 => 'Eu',
        'name_cz'                => 'europium',
        'name_en'                => 'Europium',
        'name_la'                => 'Europium',
        'periodical_group'       => null,
        'period'                 => '6',
        'atomic_weight'          => '151.964(1)',
        'density'                => '5.243',
        'melting_point'          => '1099',
        'boiling_point'          => '1802',
        'specific_heat_capacity' => '0.182',
        'electronegativity'      => '1.2',
    ],
    [
        'atomic_number'          => '64',
        'symbol'                 => 'Gd',
        'name_cz'                => 'gadolinium',
        'name_en'                => 'Gadolinium',
        'name_la'                => 'Gadolinium',
        'periodical_group'       => null,
        'period'                 => '6',
        'atomic_weight'          => '157.25(3)',
        'density'                => '7.895',
        'melting_point'          => '1585',
        'boiling_point'          => '3546',
        'specific_heat_capacity' => '0.236',
        'electronegativity'      => '1.2',
    ],
    [
        'atomic_number'          => '65',
        'symbol'                 => 'Tb',
        'name_cz'                => 'terbium',
        'name_en'                => 'Terbium',
        'name_la'                => 'Terbium',
        'periodical_group'       => null,
        'period'                 => '6',
        'atomic_weight'          => '158.925354(8)',
        'density'                => '8.229',
        'melting_point'          => '1629',
        'boiling_point'          => '3503',
        'specific_heat_capacity' => '0.182',
        'electronegativity'      => '1.2',
    ],
    [
        'atomic_number'          => '66',
        'symbol'                 => 'Dy',
        'name_cz'                => 'dysprosium',
        'name_en'                => 'Dysprosium',
        'name_la'                => 'Dysprosium',
        'periodical_group'       => null,
        'period'                 => '6',
        'atomic_weight'          => '162.500(1)',
        'density'                => '8.55',
        'melting_point'          => '1680',
        'boiling_point'          => '2840',
        'specific_heat_capacity' => '0.17',
        'electronegativity'      => '1.22',
    ],
    [
        'atomic_number'          => '67',
        'symbol'                 => 'Ho',
        'name_cz'                => 'holmium',
        'name_en'                => 'Holmium',
        'name_la'                => 'Holmium',
        'periodical_group'       => null,
        'period'                 => '6',
        'atomic_weight'          => '164.930328(7)',
        'density'                => '8.795',
        'melting_point'          => '1734',
        'boiling_point'          => '2993',
        'specific_heat_capacity' => '0.165',
        'electronegativity'      => '1.23',
    ],
    [
        'atomic_number'          => '68',
        'symbol'                 => 'Er',
        'name_cz'                => 'erbium',
        'name_en'                => 'Erbium',
        'name_la'                => 'Erbium',
        'periodical_group'       => null,
        'period'                 => '6',
        'atomic_weight'          => '167.259(3)',
        'density'                => '9.066',
        'melting_point'          => '1802',
        'boiling_point'          => '3141',
        'specific_heat_capacity' => '0.168',
        'electronegativity'      => '1.24',
    ],
    [
        'atomic_number'          => '69',
        'symbol'                 => 'Tm',
        'name_cz'                => 'thulium',
        'name_en'                => 'Thulium',
        'name_la'                => 'Thulium',
        'periodical_group'       => null,
        'period'                 => '6',
        'atomic_weight'          => '168.934218(6)',
        'density'                => '9.321',
        'melting_point'          => '1818',
        'boiling_point'          => '2223',
        'specific_heat_capacity' => '0.16',
        'electronegativity'      => '1.25',
    ],
    [
        'atomic_number'          => '70',
        'symbol'                 => 'Yb',
        'name_cz'                => 'ytterbium',
        'name_en'                => 'Ytterbium',
        'name_la'                => 'Ytterbium',
        'periodical_group'       => null,
        'period'                 => '6',
        'atomic_weight'          => '173.045(10)',
        'density'                => '6.965',
        'melting_point'          => '1097',
        'boiling_point'          => '1469',
        'specific_heat_capacity' => '0.155',
        'electronegativity'      => '1.1',
    ],
    [
        'atomic_number'          => '71',
        'symbol'                 => 'Lu',
        'name_cz'                => 'lutecium',
        'name_en'                => 'Lutetium',
        'name_la'                => 'Lutetium',
        'periodical_group'       => '3',
        'period'                 => '6',
        'atomic_weight'          => '174.9668(1)',
        'density'                => '9.84',
        'melting_point'          => '1925',
        'boiling_point'          => '3675',
        'specific_heat_capacity' => '0.154',
        'electronegativity'      => '1.27',
    ],
    [
        'atomic_number'          => '72',
        'symbol'                 => 'Hf',
        'name_cz'                => 'hafnium',
        'name_en'                => 'Hafnium',
        'name_la'                => 'Hafnium',
        'periodical_group'       => '4',
        'period'                 => '6',
        'atomic_weight'          => '178.49(2)',
        'density'                => '13.31',
        'melting_point'          => '2506',
        'boiling_point'          => '4876',
        'specific_heat_capacity' => '0.144',
        'electronegativity'      => '1.3',
    ],
    [
        'atomic_number'          => '73',
        'symbol'                 => 'Ta',
        'name_cz'                => 'tantal',
        'name_en'                => 'Tantalum',
        'name_la'                => 'Tantalum',
        'periodical_group'       => '5',
        'period'                 => '6',
        'atomic_weight'          => '180.94788(2)',
        'density'                => '16.654',
        'melting_point'          => '3290',
        'boiling_point'          => '5731',
        'specific_heat_capacity' => '0.14',
        'electronegativity'      => '1.5',
    ],
    [
        'atomic_number'          => '74',
        'symbol'                 => 'W',
        'name_cz'                => 'wolfram',
        'name_en'                => 'Tungsten',
        'name_la'                => 'Wolframium',
        'periodical_group'       => '6',
        'period'                 => '6',
        'atomic_weight'          => '183.84(1)',
        'density'                => '19.25',
        'melting_point'          => '3695',
        'boiling_point'          => '5828',
        'specific_heat_capacity' => '0.132',
        'electronegativity'      => '2.36',
    ],
    [
        'atomic_number'          => '75',
        'symbol'                 => 'Re',
        'name_cz'                => 'rhenium',
        'name_en'                => 'Rhenium',
        'name_la'                => 'Rhenium',
        'periodical_group'       => '7',
        'period'                 => '6',
        'atomic_weight'          => '186.207(1)',
        'density'                => '21.02',
        'melting_point'          => '3459',
        'boiling_point'          => '5869',
        'specific_heat_capacity' => '0.137',
        'electronegativity'      => '1.9',
    ],
    [
        'atomic_number'          => '76',
        'symbol'                 => 'Os',
        'name_cz'                => 'osmium',
        'name_en'                => 'Osmium',
        'name_la'                => 'Osmium',
        'periodical_group'       => '8',
        'period'                 => '6',
        'atomic_weight'          => '190.23(3)',
        'density'                => '22.59',
        'melting_point'          => '3306',
        'boiling_point'          => '5285',
        'specific_heat_capacity' => '0.13',
        'electronegativity'      => '2.2',
    ],
    [
        'atomic_number'          => '77',
        'symbol'                 => 'Ir',
        'name_cz'                => 'iridium',
        'name_en'                => 'Iridium',
        'name_la'                => 'Iridium',
        'periodical_group'       => '9',
        'period'                 => '6',
        'atomic_weight'          => '192.217(2)',
        'density'                => '22.56',
        'melting_point'          => '2719',
        'boiling_point'          => '4701',
        'specific_heat_capacity' => '0.131',
        'electronegativity'      => '2.2',
    ],
    [
        'atomic_number'          => '78',
        'symbol'                 => 'Pt',
        'name_cz'                => 'platina',
        'name_en'                => 'Platinum',
        'name_la'                => 'Platinum',
        'periodical_group'       => '10',
        'period'                 => '6',
        'atomic_weight'          => '195.084(9)',
        'density'                => '21.46',
        'melting_point'          => '2041.4',
        'boiling_point'          => '4098',
        'specific_heat_capacity' => '0.133',
        'electronegativity'      => '2.28',
    ],
    [
        'atomic_number'          => '79',
        'symbol'                 => 'Au',
        'name_cz'                => 'zlato',
        'name_en'                => 'Gold',
        'name_la'                => 'Aurum',
        'periodical_group'       => '11',
        'period'                 => '6',
        'atomic_weight'          => '196.966570(4)',
        'density'                => '19.282',
        'melting_point'          => '1337.33',
        'boiling_point'          => '3129',
        'specific_heat_capacity' => '0.129',
        'electronegativity'      => '2.54',
    ],
    [
        'atomic_number'          => '80',
        'symbol'                 => 'Hg',
        'name_cz'                => 'rtuť',
        'name_en'                => 'Mercury',
        'name_la'                => 'Hydrargyrum',
        'periodical_group'       => '12',
        'period'                 => '6',
        'atomic_weight'          => '200.592(3)',
        'density'                => '13.5336',
        'melting_point'          => '234.43',
        'boiling_point'          => '629.88',
        'specific_heat_capacity' => '0.14',
        'electronegativity'      => '2',
    ],
    [
        'atomic_number'          => '81',
        'symbol'                 => 'Tl',
        'name_cz'                => 'thallium',
        'name_en'                => 'Thallium',
        'name_la'                => 'Thallium',
        'periodical_group'       => '13',
        'period'                 => '6',
        'atomic_weight'          => '204.38',
        'density'                => '11.85',
        'melting_point'          => '577',
        'boiling_point'          => '1746',
        'specific_heat_capacity' => '0.129',
        'electronegativity'      => '1.62',
    ],
    [
        'atomic_number'          => '82',
        'symbol'                 => 'Pb',
        'name_cz'                => 'olovo',
        'name_en'                => 'Lead',
        'name_la'                => 'Plumbum',
        'periodical_group'       => '14',
        'period'                 => '6',
        'atomic_weight'          => '207.2(1)',
        'density'                => '11.342',
        'melting_point'          => '600.61',
        'boiling_point'          => '2022',
        'specific_heat_capacity' => '0.129',
        'electronegativity'      => '1.87',
    ],
    [
        'atomic_number'          => '83',
        'symbol'                 => 'Bi',
        'name_cz'                => 'bismut',
        'name_en'                => 'Bismuth',
        'name_la'                => 'Bisemutum',
        'periodical_group'       => '15',
        'period'                 => '6',
        'atomic_weight'          => '208.98040(1)',
        'density'                => '9.807',
        'melting_point'          => '544.7',
        'boiling_point'          => '1837',
        'specific_heat_capacity' => '0.122',
        'electronegativity'      => '2.02',
    ],
    [
        'atomic_number'          => '84',
        'symbol'                 => 'Po',
        'name_cz'                => 'polonium',
        'name_en'                => 'Polonium',
        'name_la'                => 'Polonium',
        'periodical_group'       => '16',
        'period'                 => '6',
        'atomic_weight'          => '[209]',
        'density'                => '9.32',
        'melting_point'          => '527',
        'boiling_point'          => '1235',
        'specific_heat_capacity' => null,
        'electronegativity'      => '2',
    ],
    [
        'atomic_number'          => '85',
        'symbol'                 => 'At',
        'name_cz'                => 'astat',
        'name_en'                => 'Astatine',
        'name_la'                => 'Astatinum',
        'periodical_group'       => '17',
        'period'                 => '6',
        'atomic_weight'          => '[210]',
        'density'                => '7',
        'melting_point'          => '575',
        'boiling_point'          => '610',
        'specific_heat_capacity' => null,
        'electronegativity'      => '2.2',
    ],
    [
        'atomic_number'          => '86',
        'symbol'                 => 'Rn',
        'name_cz'                => 'radon',
        'name_en'                => 'Radon',
        'name_la'                => 'Radon',
        'periodical_group'       => '18',
        'period'                 => '6',
        'atomic_weight'          => '[222]',
        'density'                => '0.00973',
        'melting_point'          => '202',
        'boiling_point'          => '211.3',
        'specific_heat_capacity' => '0.094',
        'electronegativity'      => '2.2',
    ],
    [
        'atomic_number'          => '87',
        'symbol'                 => 'Fr',
        'name_cz'                => 'francium',
        'name_en'                => 'Francium',
        'name_la'                => 'Francium',
        'periodical_group'       => '1',
        'period'                 => '7',
        'atomic_weight'          => '[223]',
        'density'                => '1.87',
        'melting_point'          => '281',
        'boiling_point'          => '890',
        'specific_heat_capacity' => null,
        'electronegativity'      => '0.7',
    ],
    [
        'atomic_number'          => '88',
        'symbol'                 => 'Ra',
        'name_cz'                => 'radium',
        'name_en'                => 'Radium',
        'name_la'                => 'Radium',
        'periodical_group'       => '2',
        'period'                 => '7',
        'atomic_weight'          => '[226]',
        'density'                => '5.5',
        'melting_point'          => '973',
        'boiling_point'          => '2010',
        'specific_heat_capacity' => '0.094',
        'electronegativity'      => '0.9',
    ],
    [
        'atomic_number'          => '89',
        'symbol'                 => 'Ac',
        'name_cz'                => 'aktinium',
        'name_en'                => 'Actinium',
        'name_la'                => 'Actinium',
        'periodical_group'       => null,
        'period'                 => '7',
        'atomic_weight'          => '[227]',
        'density'                => '10.07',
        'melting_point'          => '1323',
        'boiling_point'          => '3471',
        'specific_heat_capacity' => '0.12',
        'electronegativity'      => '1.1',
    ],
    [
        'atomic_number'          => '90',
        'symbol'                 => 'Th',
        'name_cz'                => 'thorium',
        'name_en'                => 'Thorium',
        'name_la'                => 'Thorium',
        'periodical_group'       => null,
        'period'                 => '7',
        'atomic_weight'          => '232.0377(4)',
        'density'                => '11.72',
        'melting_point'          => '2115',
        'boiling_point'          => '5061',
        'specific_heat_capacity' => '0.113',
        'electronegativity'      => '1.3',
    ],
    [
        'atomic_number'          => '91',
        'symbol'                 => 'Pa',
        'name_cz'                => 'protaktinium',
        'name_en'                => 'Protactinium',
        'name_la'                => 'Protactinium',
        'periodical_group'       => null,
        'period'                 => '7',
        'atomic_weight'          => '231.03588(1)',
        'density'                => '15.37',
        'melting_point'          => '1841',
        'boiling_point'          => '4300',
        'specific_heat_capacity' => null,
        'electronegativity'      => '1.5',
    ],
    [
        'atomic_number'          => '92',
        'symbol'                 => 'U',
        'name_cz'                => 'uran',
        'name_en'                => 'Uranium',
        'name_la'                => 'Uranium',
        'periodical_group'       => null,
        'period'                 => '7',
        'atomic_weight'          => '238.02891(3)',
        'density'                => '18.95',
        'melting_point'          => '1405.3',
        'boiling_point'          => '4404',
        'specific_heat_capacity' => '0.116',
        'electronegativity'      => '1.38',
    ],
    [
        'atomic_number'          => '93',
        'symbol'                 => 'Np',
        'name_cz'                => 'neptunium',
        'name_en'                => 'Neptunium',
        'name_la'                => 'Neptunium',
        'periodical_group'       => null,
        'period'                 => '7',
        'atomic_weight'          => '[237]',
        'density'                => '20.45',
        'melting_point'          => '917',
        'boiling_point'          => '4273',
        'specific_heat_capacity' => null,
        'electronegativity'      => '1.36',
    ],
    [
        'atomic_number'          => '94',
        'symbol'                 => 'Pu',
        'name_cz'                => 'plutonium',
        'name_en'                => 'Plutonium',
        'name_la'                => 'Plutonium',
        'periodical_group'       => null,
        'period'                 => '7',
        'atomic_weight'          => '[244]',
        'density'                => '19.85',
        'melting_point'          => '912.5',
        'boiling_point'          => '3501',
        'specific_heat_capacity' => null,
        'electronegativity'      => '1.28',
    ],
    [
        'atomic_number'          => '95',
        'symbol'                 => 'Am',
        'name_cz'                => 'americium',
        'name_en'                => 'Americium',
        'name_la'                => 'Americium',
        'periodical_group'       => null,
        'period'                 => '7',
        'atomic_weight'          => '[243]',
        'density'                => '13.69',
        'melting_point'          => '1449',
        'boiling_point'          => '2880',
        'specific_heat_capacity' => null,
        'electronegativity'      => '1.13',
    ],
    [
        'atomic_number'          => '96',
        'symbol'                 => 'Cm',
        'name_cz'                => 'curium',
        'name_en'                => 'Curium',
        'name_la'                => 'Curium',
        'periodical_group'       => null,
        'period'                 => '7',
        'atomic_weight'          => '[247]',
        'density'                => '13.51',
        'melting_point'          => '1613',
        'boiling_point'          => '3383',
        'specific_heat_capacity' => null,
        'electronegativity'      => '1.28',
    ],
    [
        'atomic_number'          => '97',
        'symbol'                 => 'Bk',
        'name_cz'                => 'berkelium',
        'name_en'                => 'Berkelium',
        'name_la'                => 'Berkelium',
        'periodical_group'       => null,
        'period'                 => '7',
        'atomic_weight'          => '[247]',
        'density'                => '14.79',
        'melting_point'          => '1259',
        'boiling_point'          => '2900',
        'specific_heat_capacity' => null,
        'electronegativity'      => '1.3',
    ],
    [
        'atomic_number'          => '98',
        'symbol'                 => 'Cf',
        'name_cz'                => 'kalifornium',
        'name_en'                => 'Californium',
        'name_la'                => 'Californium',
        'periodical_group'       => null,
        'period'                 => '7',
        'atomic_weight'          => '[251]',
        'density'                => '15.1',
        'melting_point'          => '1173',
        'boiling_point'          => '-1743',
        'specific_heat_capacity' => null,
        'electronegativity'      => '1.3',
    ],
    [
        'atomic_number'          => '99',
        'symbol'                 => 'Es',
        'name_cz'                => 'einsteinium',
        'name_en'                => 'Einsteinium',
        'name_la'                => 'Einsteinium',
        'periodical_group'       => null,
        'period'                 => '7',
        'atomic_weight'          => '[252]',
        'density'                => '8.84',
        'melting_point'          => '1133',
        'boiling_point'          => '-1269',
        'specific_heat_capacity' => null,
        'electronegativity'      => '1.3',
    ],
    [
        'atomic_number'          => '100',
        'symbol'                 => 'Fm',
        'name_cz'                => 'fermium',
        'name_en'                => 'Fermium',
        'name_la'                => 'Fermium',
        'periodical_group'       => null,
        'period'                 => '7',
        'atomic_weight'          => '[257]',
        'density'                => '0',
        'melting_point'          => '-1125',
        'boiling_point'          => null,
        'specific_heat_capacity' => null,
        'electronegativity'      => '1.3',
    ],
    [
        'atomic_number'          => '101',
        'symbol'                 => 'Md',
        'name_cz'                => 'mendelevium',
        'name_en'                => 'Mendelevium',
        'name_la'                => 'Mendelevium',
        'periodical_group'       => null,
        'period'                 => '7',
        'atomic_weight'          => '[258]',
        'density'                => '0',
        'melting_point'          => '-1100',
        'boiling_point'          => null,
        'specific_heat_capacity' => null,
        'electronegativity'      => '1.3',
    ],
    [
        'atomic_number'          => '102',
        'symbol'                 => 'No',
        'name_cz'                => 'nobelium',
        'name_en'                => 'Nobelium',
        'name_la'                => 'Nobelium',
        'periodical_group'       => null,
        'period'                 => '7',
        'atomic_weight'          => '[259]',
        'density'                => '0',
        'melting_point'          => '-1100',
        'boiling_point'          => null,
        'specific_heat_capacity' => null,
        'electronegativity'      => '1.3',
    ],
    [
        'atomic_number'          => '103',
        'symbol'                 => 'Lr',
        'name_cz'                => 'lawrencium',
        'name_en'                => 'Lawrencium',
        'name_la'                => 'Lawrencium',
        'periodical_group'       => '3',
        'period'                 => '7',
        'atomic_weight'          => '[266]',
        'density'                => '0',
        'melting_point'          => '-1900',
        'boiling_point'          => null,
        'specific_heat_capacity' => null,
        'electronegativity'      => '1.3',
    ],
    [
        'atomic_number'          => '104',
        'symbol'                 => 'Rf',
        'name_cz'                => 'rutherfordium',
        'name_en'                => 'Rutherfordium',
        'name_la'                => 'Rutherfordium',
        'periodical_group'       => '4',
        'period'                 => '7',
        'atomic_weight'          => '[267]',
        'density'                => '0',
        'melting_point'          => '-2400',
        'boiling_point'          => '-5800',
        'specific_heat_capacity' => null,
        'electronegativity'      => '0',
    ],
    [
        'atomic_number'          => '105',
        'symbol'                 => 'Db',
        'name_cz'                => 'dubnium',
        'name_en'                => 'Dubnium',
        'name_la'                => 'Dubnium',
        'periodical_group'       => '5',
        'period'                 => '7',
        'atomic_weight'          => '[268]',
        'density'                => '0',
        'melting_point'          => null,
        'boiling_point'          => null,
        'specific_heat_capacity' => null,
        'electronegativity'      => '0',
    ],
    [
        'atomic_number'          => '106',
        'symbol'                 => 'Sg',
        'name_cz'                => 'seaborgium',
        'name_en'                => 'Seaborgium',
        'name_la'                => 'Seaborgium',
        'periodical_group'       => '6',
        'period'                 => '7',
        'atomic_weight'          => '[269]',
        'density'                => '0',
        'melting_point'          => null,
        'boiling_point'          => null,
        'specific_heat_capacity' => null,
        'electronegativity'      => '0',
    ],
    [
        'atomic_number'          => '107',
        'symbol'                 => 'Bh',
        'name_cz'                => 'bohrium',
        'name_en'                => 'Bohrium',
        'name_la'                => 'Bohrium',
        'periodical_group'       => '7',
        'period'                 => '7',
        'atomic_weight'          => '[270]',
        'density'                => '0',
        'melting_point'          => null,
        'boiling_point'          => null,
        'specific_heat_capacity' => null,
        'electronegativity'      => '0',
    ],
    [
        'atomic_number'          => '108',
        'symbol'                 => 'Hs',
        'name_cz'                => 'hassium',
        'name_en'                => 'Hassium',
        'name_la'                => 'Hassium',
        'periodical_group'       => '8',
        'period'                 => '7',
        'atomic_weight'          => '[270]',
        'density'                => '0',
        'melting_point'          => null,
        'boiling_point'          => null,
        'specific_heat_capacity' => null,
        'electronegativity'      => '0',
    ],
    [
        'atomic_number'          => '109',
        'symbol'                 => 'Mt',
        'name_cz'                => 'meitnerium',
        'name_en'                => 'Meitnerium',
        'name_la'                => 'Meitnerium',
        'periodical_group'       => '9',
        'period'                 => '7',
        'atomic_weight'          => '[278]',
        'density'                => '0',
        'melting_point'          => null,
        'boiling_point'          => null,
        'specific_heat_capacity' => null,
        'electronegativity'      => '0',
    ],
    [
        'atomic_number'          => '110',
        'symbol'                 => 'Ds',
        'name_cz'                => 'darmstadtium',
        'name_en'                => 'Darmstadtium',
        'name_la'                => 'Darmstadtium',
        'periodical_group'       => '10',
        'period'                 => '7',
        'atomic_weight'          => '[281]',
        'density'                => '0',
        'melting_point'          => null,
        'boiling_point'          => null,
        'specific_heat_capacity' => null,
        'electronegativity'      => '0',
    ],
    [
        'atomic_number'          => '111',
        'symbol'                 => 'Rg',
        'name_cz'                => 'roentgenium',
        'name_en'                => 'Roentgenium',
        'name_la'                => 'Roentgenium*',
        'periodical_group'       => '11',
        'period'                 => '7',
        'atomic_weight'          => '[282]',
        'density'                => '0',
        'melting_point'          => null,
        'boiling_point'          => null,
        'specific_heat_capacity' => null,
        'electronegativity'      => '0',
    ],
    [
        'atomic_number'          => '112',
        'symbol'                 => 'Cn',
        'name_cz'                => 'kopernicium',
        'name_en'                => 'Copernicium',
        'name_la'                => 'Copernicium*',
        'periodical_group'       => '12',
        'period'                 => '7',
        'atomic_weight'          => '[285]',
        'density'                => '0',
        'melting_point'          => '-283',
        'boiling_point'          => '-340',
        'specific_heat_capacity' => null,
        'electronegativity'      => '0',
    ],
    [
        'atomic_number'          => '113',
        'symbol'                 => 'Nh',
        'name_cz'                => 'nihonium',
        'name_en'                => 'Nihonium',
        'name_la'                => 'Nihonium*',
        'periodical_group'       => '13',
        'period'                 => '7',
        'atomic_weight'          => '[286]',
        'density'                => '-16',
        'melting_point'          => '-700',
        'boiling_point'          => '-1400',
        'specific_heat_capacity' => null,
        'electronegativity'      => '0',
    ],
    [
        'atomic_number'          => '114',
        'symbol'                 => 'Fl',
        'name_cz'                => 'flerovium',
        'name_en'                => 'Flerovium',
        'name_la'                => 'Flerovium*',
        'periodical_group'       => '14',
        'period'                 => '7',
        'atomic_weight'          => '[289]',
        'density'                => '0',
        'melting_point'          => '-200',
        'boiling_point'          => '-380',
        'specific_heat_capacity' => null,
        'electronegativity'      => '0',
    ],
    [
        'atomic_number'          => '115',
        'symbol'                 => 'Mc',
        'name_cz'                => 'moscovium',
        'name_en'                => 'Moscovium',
        'name_la'                => 'Moscovium*',
        'periodical_group'       => '15',
        'period'                 => '7',
        'atomic_weight'          => '[290]',
        'density'                => '0',
        'melting_point'          => '-700',
        'boiling_point'          => '-1400',
        'specific_heat_capacity' => null,
        'electronegativity'      => '0',
    ],
    [
        'atomic_number'          => '116',
        'symbol'                 => 'Lv',
        'name_cz'                => 'livermorium',
        'name_en'                => 'Livermorium',
        'name_la'                => 'Livermorium*',
        'periodical_group'       => '16',
        'period'                 => '7',
        'atomic_weight'          => '[293]',
        'density'                => '0',
        'melting_point'          => '-700',
        'boiling_point'          => '-1100',
        'specific_heat_capacity' => null,
        'electronegativity'      => '0',
    ],
    [
        'atomic_number'          => '117',
        'symbol'                 => 'Ts',
        'name_cz'                => 'tennessin',
        'name_en'                => 'Tennessine',
        'name_la'                => 'Tennessine*',
        'periodical_group'       => '17',
        'period'                 => '7',
        'atomic_weight'          => '[294]',
        'density'                => '0',
        'melting_point'          => '-700',
        'boiling_point'          => '-883',
        'specific_heat_capacity' => null,
        'electronegativity'      => '0',
    ],
    [
        'atomic_number'          => '118',
        'symbol'                 => 'Og',
        'name_cz'                => 'oganesson',
        'name_en'                => 'Oganesson',
        'name_la'                => 'Oganesson*',
        'periodical_group'       => '18',
        'period'                 => '7',
        'atomic_weight'          => '[294]',
        'density'                => '-7',
        'melting_point'          => '-325',
        'boiling_point'          => '-450',
        'specific_heat_capacity' => null,
        'electronegativity'      => '0',
    ],
];
